# Generated by Django 4.2.10 on 2024-02-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='type',
            name='max_players',
            field=models.IntegerField(verbose_name='Max number of players'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(choices=[('A', 'Adventure'), ('F', 'Fantasy'), ('R', 'RPG'), ('B', 'Fighting'), ('S', 'Shooter'), ('O', 'Other')], default='A', max_length=1),
        ),
    ]
