# Generated by Django 4.2.10 on 2024-02-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_console_alter_type_max_players_alter_type_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='consoles',
            field=models.ManyToManyField(to='main_app.console'),
        ),
    ]
